### ISSUE TITLE
缺少系统启动环境说明和使用说明

### ISSUE THREAD

**Issue by fjtatanet** [xhwanhaoran/ssm#2]
希望在README.md中增加，
1. 用tomcat或jetty哪个版本启动？
2. 启动后，前台输入uri的demo

**Comment by NightFlightCaptain** [comment]
tomcat采用7.0版本，不过实际上8.0应该也可以。
该项目是前后端分离项目，没有前端页面，采用的是swagger2接口文档的模式。进入路径是swagger-ui.html
