### ISSUE TITLE
一个小蒟蒻的提问

### ISSUE THREAD

**Issue by huangqianhong** [xhwanhaoran/ssm#4]
你好，我先请问一下，你的项目中不是有前后端分离吗？前后端分离后，前端的页面保存在哪呀？

**Comment by NightFlightCaptain** [comment]
这个项目没有前端，只有后端部分；前后端分离是指前端和后端完全分离开来，所以可以很方便的将前端集成进来。

**Comment by huangqianhong** [comment]
谢谢了，最近在学前后端分离，想尝试一下这个项目

**Comment by NightFlightCaptain** [comment]
建议先看一下spring的ioc,aop等等的含义与大体上的实现；springmvc的流程顺序，拦截器的基本原理等等

**Comment by huangqianhong** [comment]
我之前自学了spring的框架还有springMVC和mybatis这些框架，准备做一个这样的试试，看看可不可以去找个实习
